version: 2
snapshot:
  widths:
    - 414
    - 1280
  minHeight: 1024
  percyCSS: ""
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
  disableCache: true
  launchOptions:
    headless: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
static:
  baseUrl: /
  files: "**/*.{html,htm}"
  ignore: ""
